INSERT INTO MX_MAQUINARIA(ID, NOMBRE, DESCRIPCION, CANTIDAD, EMPRESA_ID) VALUES
(1,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,5),
(2,'Cortador anular','Cortadores anulares a disposición de la empresa',4,5),
(3,'Segueta','Seguetas a disposición de la empresa',4,5),
(4,'Sierra circular','Sierras circulares a disposición de la empresa',4,5),
(5,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,5),
(6,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,5),
(7,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,5),
(8,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,5),
(9,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,5),
(10,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,5),
(11,'Excavadora','Excavadoras a disposición de la empresa',2,5),
(12,'Perforadora','Perforadoras a disposición de la empresa',2,5),
(13,'Rodillo','Rodillos a disposición de la empresa',2,5),
(14,'Tractor oruga','Tractores oruga a disposición de la empresa',2,5),
(15,'Camioneta','Camionetas a disposición de la empresa',2,5),
(16,'Bus','Buses a disposición de la empresa',2,5),
(17,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,5),
(18,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,5),
(19,'Camión grúa','Camiones grúa a disposición de la empresa',2,5),
(20,'Camión bombero','Camiones bombero a disposición de la empresa',2,5),
(21,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,6),
(22,'Cortador anular','Cortadores anulares a disposición de la empresa',4,6),
(23,'Segueta','Seguetas a disposición de la empresa',4,6),
(24,'Sierra circular','Sierras circulares a disposición de la empresa',4,6),
(25,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,6),
(26,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,6),
(27,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,6),
(28,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,6),
(29,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,6),
(30,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,6),
(31,'Excavadora','Excavadoras a disposición de la empresa',2,6),
(32,'Perforadora','Perforadoras a disposición de la empresa',2,6),
(33,'Rodillo','Rodillos a disposición de la empresa',2,6),
(34,'Tractor oruga','Tractores oruga a disposición de la empresa',2,6),
(35,'Camioneta','Camionetas a disposición de la empresa',2,6),
(36,'Bus','Buses a disposición de la empresa',2,6),
(37,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,6),
(38,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,6),
(39,'Camión grúa','Camiones grúa a disposición de la empresa',2,6),
(40,'Camión bombero','Camiones bombero a disposición de la empresa',2,6),
(41,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,11),
(42,'Cortador anular','Cortadores anulares a disposición de la empresa',4,11),
(43,'Segueta','Seguetas a disposición de la empresa',4,11),
(44,'Sierra circular','Sierras circulares a disposición de la empresa',4,11),
(45,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,11),
(46,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,11),
(47,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,11),
(48,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,11),
(49,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,11),
(50,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,11),
(51,'Excavadora','Excavadoras a disposición de la empresa',2,11),
(52,'Perforadora','Perforadoras a disposición de la empresa',2,11),
(53,'Rodillo','Rodillos a disposición de la empresa',2,11),
(54,'Tractor oruga','Tractores oruga a disposición de la empresa',2,11),
(55,'Camioneta','Camionetas a disposición de la empresa',2,11),
(56,'Bus','Buses a disposición de la empresa',2,11),
(57,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,11),
(58,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,11),
(59,'Camión grúa','Camiones grúa a disposición de la empresa',2,11),
(60,'Camión bombero','Camiones bombero a disposición de la empresa',2,11),
(61,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,12),
(62,'Cortador anular','Cortadores anulares a disposición de la empresa',4,12),
(63,'Segueta','Seguetas a disposición de la empresa',4,12),
(64,'Sierra circular','Sierras circulares a disposición de la empresa',4,12),
(65,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,12),
(66,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,12),
(67,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,12),
(68,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,12),
(69,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,12),
(70,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,12),
(71,'Excavadora','Excavadoras a disposición de la empresa',2,12),
(72,'Perforadora','Perforadoras a disposición de la empresa',2,12),
(73,'Rodillo','Rodillos a disposición de la empresa',2,12),
(74,'Tractor oruga','Tractores oruga a disposición de la empresa',2,12),
(75,'Camioneta','Camionetas a disposición de la empresa',2,12),
(76,'Bus','Buses a disposición de la empresa',2,12),
(77,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,12),
(78,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,12),
(79,'Camión grúa','Camiones grúa a disposición de la empresa',2,12),
(80,'Camión bombero','Camiones bombero a disposición de la empresa',2,12),
(81,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,17),
(82,'Cortador anular','Cortadores anulares a disposición de la empresa',4,17),
(83,'Segueta','Seguetas a disposición de la empresa',4,17),
(84,'Sierra circular','Sierras circulares a disposición de la empresa',4,17),
(85,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,17),
(86,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,17),
(87,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,17),
(88,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,17),
(89,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,17),
(90,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,17),
(91,'Excavadora','Excavadoras a disposición de la empresa',2,17),
(92,'Perforadora','Perforadoras a disposición de la empresa',2,17),
(93,'Rodillo','Rodillos a disposición de la empresa',2,17),
(94,'Tractor oruga','Tractores oruga a disposición de la empresa',2,17),
(95,'Camioneta','Camionetas a disposición de la empresa',2,17),
(96,'Bus','Buses a disposición de la empresa',2,17),
(97,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,17),
(98,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,17),
(99,'Camión grúa','Camiones grúa a disposición de la empresa',2,17),
(100,'Camión bombero','Camiones bombero a disposición de la empresa',2,17),
(101,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,18),
(102,'Cortador anular','Cortadores anulares a disposición de la empresa',4,18),
(103,'Segueta','Seguetas a disposición de la empresa',4,18),
(104,'Sierra circular','Sierras circulares a disposición de la empresa',4,18),
(105,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,18),
(106,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,18),
(107,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,18),
(108,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,18),
(109,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,18),
(110,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,18),
(111,'Excavadora','Excavadoras a disposición de la empresa',2,18),
(112,'Perforadora','Perforadoras a disposición de la empresa',2,18),
(113,'Rodillo','Rodillos a disposición de la empresa',2,18),
(114,'Tractor oruga','Tractores oruga a disposición de la empresa',2,18),
(115,'Camioneta','Camionetas a disposición de la empresa',2,18),
(116,'Bus','Buses a disposición de la empresa',2,18),
(117,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,18),
(118,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,18),
(119,'Camión grúa','Camiones grúa a disposición de la empresa',2,18),
(120,'Camión bombero','Camiones bombero a disposición de la empresa',2,18),
(121,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,23),
(122,'Cortador anular','Cortadores anulares a disposición de la empresa',4,23),
(123,'Segueta','Seguetas a disposición de la empresa',4,23),
(124,'Sierra circular','Sierras circulares a disposición de la empresa',4,23),
(125,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,23),
(126,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,23),
(127,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,23),
(128,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,23),
(129,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,23),
(130,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,23),
(131,'Excavadora','Excavadoras a disposición de la empresa',2,23),
(132,'Perforadora','Perforadoras a disposición de la empresa',2,23),
(133,'Rodillo','Rodillos a disposición de la empresa',2,23),
(134,'Tractor oruga','Tractores oruga a disposición de la empresa',2,23),
(135,'Camioneta','Camionetas a disposición de la empresa',2,23),
(136,'Bus','Buses a disposición de la empresa',2,23),
(137,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,23),
(138,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,23),
(139,'Camión grúa','Camiones grúa a disposición de la empresa',2,23),
(140,'Camión bombero','Camiones bombero a disposición de la empresa',2,23),
(141,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,24),
(142,'Cortador anular','Cortadores anulares a disposición de la empresa',4,24),
(143,'Segueta','Seguetas a disposición de la empresa',4,24),
(144,'Sierra circular','Sierras circulares a disposición de la empresa',4,24),
(145,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,24),
(146,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,24),
(147,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,24),
(148,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,24),
(149,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,24),
(150,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,24),
(151,'Excavadora','Excavadoras a disposición de la empresa',2,24),
(152,'Perforadora','Perforadoras a disposición de la empresa',2,24),
(153,'Rodillo','Rodillos a disposición de la empresa',2,24),
(154,'Tractor oruga','Tractores oruga a disposición de la empresa',2,24),
(155,'Camioneta','Camionetas a disposición de la empresa',2,24),
(156,'Bus','Buses a disposición de la empresa',2,24),
(157,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,24),
(158,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,24),
(159,'Camión grúa','Camiones grúa a disposición de la empresa',2,24),
(160,'Camión bombero','Camiones bombero a disposición de la empresa',2,24),
(161,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,29),
(162,'Cortador anular','Cortadores anulares a disposición de la empresa',4,29),
(163,'Segueta','Seguetas a disposición de la empresa',4,29),
(164,'Sierra circular','Sierras circulares a disposición de la empresa',4,29),
(165,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,29),
(166,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,29),
(167,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,29),
(168,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,29),
(169,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,29),
(170,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,29),
(171,'Excavadora','Excavadoras a disposición de la empresa',2,29),
(172,'Perforadora','Perforadoras a disposición de la empresa',2,29),
(173,'Rodillo','Rodillos a disposición de la empresa',2,29),
(174,'Tractor oruga','Tractores oruga a disposición de la empresa',2,29),
(175,'Camioneta','Camionetas a disposición de la empresa',2,29),
(176,'Bus','Buses a disposición de la empresa',2,29),
(177,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,29),
(178,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,29),
(179,'Camión grúa','Camiones grúa a disposición de la empresa',2,29),
(180,'Camión bombero','Camiones bombero a disposición de la empresa',2,29),
(181,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,30),
(182,'Cortador anular','Cortadores anulares a disposición de la empresa',4,30),
(183,'Segueta','Seguetas a disposición de la empresa',4,30),
(184,'Sierra circular','Sierras circulares a disposición de la empresa',4,30),
(185,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,30),
(186,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,30),
(187,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,30),
(188,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,30),
(189,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,30),
(190,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,30),
(191,'Excavadora','Excavadoras a disposición de la empresa',2,30),
(192,'Perforadora','Perforadoras a disposición de la empresa',2,30),
(193,'Rodillo','Rodillos a disposición de la empresa',2,30),
(194,'Tractor oruga','Tractores oruga a disposición de la empresa',2,30),
(195,'Camioneta','Camionetas a disposición de la empresa',2,30),
(196,'Bus','Buses a disposición de la empresa',2,30),
(197,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,30),
(198,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,30),
(199,'Camión grúa','Camiones grúa a disposición de la empresa',2,30),
(200,'Camión bombero','Camiones bombero a disposición de la empresa',2,30),
(201,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,35),
(202,'Cortador anular','Cortadores anulares a disposición de la empresa',4,35),
(203,'Segueta','Seguetas a disposición de la empresa',4,35),
(204,'Sierra circular','Sierras circulares a disposición de la empresa',4,35),
(205,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,35),
(206,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,35),
(207,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,35),
(208,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,35),
(209,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,35),
(210,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,35),
(211,'Excavadora','Excavadoras a disposición de la empresa',2,35),
(212,'Perforadora','Perforadoras a disposición de la empresa',2,35),
(213,'Rodillo','Rodillos a disposición de la empresa',2,35),
(214,'Tractor oruga','Tractores oruga a disposición de la empresa',2,35),
(215,'Camioneta','Camionetas a disposición de la empresa',2,35),
(216,'Bus','Buses a disposición de la empresa',2,35),
(217,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,35),
(218,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,35),
(219,'Camión grúa','Camiones grúa a disposición de la empresa',2,35),
(220,'Camión bombero','Camiones bombero a disposición de la empresa',2,35),
(221,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,36),
(222,'Cortador anular','Cortadores anulares a disposición de la empresa',4,36),
(223,'Segueta','Seguetas a disposición de la empresa',4,36),
(224,'Sierra circular','Sierras circulares a disposición de la empresa',4,36),
(225,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,36),
(226,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,36),
(227,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,36),
(228,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,36),
(229,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,36),
(230,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,36),
(231,'Excavadora','Excavadoras a disposición de la empresa',2,36),
(232,'Perforadora','Perforadoras a disposición de la empresa',2,36),
(233,'Rodillo','Rodillos a disposición de la empresa',2,36),
(234,'Tractor oruga','Tractores oruga a disposición de la empresa',2,36),
(235,'Camioneta','Camionetas a disposición de la empresa',2,36),
(236,'Bus','Buses a disposición de la empresa',2,36),
(237,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,36),
(238,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,36),
(239,'Camión grúa','Camiones grúa a disposición de la empresa',2,36),
(240,'Camión bombero','Camiones bombero a disposición de la empresa',2,36),
(241,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,41),
(242,'Cortador anular','Cortadores anulares a disposición de la empresa',4,41),
(243,'Segueta','Seguetas a disposición de la empresa',4,41),
(244,'Sierra circular','Sierras circulares a disposición de la empresa',4,41),
(245,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,41),
(246,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,41),
(247,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,41),
(248,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,41),
(249,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,41),
(250,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,41),
(251,'Excavadora','Excavadoras a disposición de la empresa',2,41),
(252,'Perforadora','Perforadoras a disposición de la empresa',2,41),
(253,'Rodillo','Rodillos a disposición de la empresa',2,41),
(254,'Tractor oruga','Tractores oruga a disposición de la empresa',2,41),
(255,'Camioneta','Camionetas a disposición de la empresa',2,41),
(256,'Bus','Buses a disposición de la empresa',2,41),
(257,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,41),
(258,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,41),
(259,'Camión grúa','Camiones grúa a disposición de la empresa',2,41),
(260,'Camión bombero','Camiones bombero a disposición de la empresa',2,41),
(261,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,42),
(262,'Cortador anular','Cortadores anulares a disposición de la empresa',4,42),
(263,'Segueta','Seguetas a disposición de la empresa',4,42),
(264,'Sierra circular','Sierras circulares a disposición de la empresa',4,42),
(265,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,42),
(266,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,42),
(267,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,42),
(268,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,42),
(269,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,42),
(270,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,42),
(271,'Excavadora','Excavadoras a disposición de la empresa',2,42),
(272,'Perforadora','Perforadoras a disposición de la empresa',2,42),
(273,'Rodillo','Rodillos a disposición de la empresa',2,42),
(274,'Tractor oruga','Tractores oruga a disposición de la empresa',2,42),
(275,'Camioneta','Camionetas a disposición de la empresa',2,42),
(276,'Bus','Buses a disposición de la empresa',2,42),
(277,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,42),
(278,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,42),
(279,'Camión grúa','Camiones grúa a disposición de la empresa',2,42),
(280,'Camión bombero','Camiones bombero a disposición de la empresa',2,42),
(281,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,47),
(282,'Cortador anular','Cortadores anulares a disposición de la empresa',4,47),
(283,'Segueta','Seguetas a disposición de la empresa',4,47),
(284,'Sierra circular','Sierras circulares a disposición de la empresa',4,47),
(285,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,47),
(286,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,47),
(287,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,47),
(288,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,47),
(289,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,47),
(290,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,47),
(291,'Excavadora','Excavadoras a disposición de la empresa',2,47),
(292,'Perforadora','Perforadoras a disposición de la empresa',2,47),
(293,'Rodillo','Rodillos a disposición de la empresa',2,47),
(294,'Tractor oruga','Tractores oruga a disposición de la empresa',2,47),
(295,'Camioneta','Camionetas a disposición de la empresa',2,47),
(296,'Bus','Buses a disposición de la empresa',2,47),
(297,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,47),
(298,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,47),
(299,'Camión grúa','Camiones grúa a disposición de la empresa',2,47),
(300,'Camión bombero','Camiones bombero a disposición de la empresa',2,47),
(301,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,48),
(302,'Cortador anular','Cortadores anulares a disposición de la empresa',4,48),
(303,'Segueta','Seguetas a disposición de la empresa',4,48),
(304,'Sierra circular','Sierras circulares a disposición de la empresa',4,48),
(305,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,48),
(306,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,48),
(307,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,48),
(308,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,48),
(309,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,48),
(310,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,48),
(311,'Excavadora','Excavadoras a disposición de la empresa',2,48),
(312,'Perforadora','Perforadoras a disposición de la empresa',2,48),
(313,'Rodillo','Rodillos a disposición de la empresa',2,48),
(314,'Tractor oruga','Tractores oruga a disposición de la empresa',2,48),
(315,'Camioneta','Camionetas a disposición de la empresa',2,48),
(316,'Bus','Buses a disposición de la empresa',2,48),
(317,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,48),
(318,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,48),
(319,'Camión grúa','Camiones grúa a disposición de la empresa',2,48),
(320,'Camión bombero','Camiones bombero a disposición de la empresa',2,48),
(321,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,53),
(322,'Cortador anular','Cortadores anulares a disposición de la empresa',4,53),
(323,'Segueta','Seguetas a disposición de la empresa',4,53),
(324,'Sierra circular','Sierras circulares a disposición de la empresa',4,53),
(325,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,53),
(326,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,53),
(327,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,53),
(328,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,53),
(329,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,53),
(330,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,53),
(331,'Excavadora','Excavadoras a disposición de la empresa',2,53),
(332,'Perforadora','Perforadoras a disposición de la empresa',2,53),
(333,'Rodillo','Rodillos a disposición de la empresa',2,53),
(334,'Tractor oruga','Tractores oruga a disposición de la empresa',2,53),
(335,'Camioneta','Camionetas a disposición de la empresa',2,53),
(336,'Bus','Buses a disposición de la empresa',2,53),
(337,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,53),
(338,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,53),
(339,'Camión grúa','Camiones grúa a disposición de la empresa',2,53),
(340,'Camión bombero','Camiones bombero a disposición de la empresa',2,53),
(341,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,54),
(342,'Cortador anular','Cortadores anulares a disposición de la empresa',4,54),
(343,'Segueta','Seguetas a disposición de la empresa',4,54),
(344,'Sierra circular','Sierras circulares a disposición de la empresa',4,54),
(345,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,54),
(346,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,54),
(347,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,54),
(348,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,54),
(349,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,54),
(350,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,54),
(351,'Excavadora','Excavadoras a disposición de la empresa',2,54),
(352,'Perforadora','Perforadoras a disposición de la empresa',2,54),
(353,'Rodillo','Rodillos a disposición de la empresa',2,54),
(354,'Tractor oruga','Tractores oruga a disposición de la empresa',2,54),
(355,'Camioneta','Camionetas a disposición de la empresa',2,54),
(356,'Bus','Buses a disposición de la empresa',2,54),
(357,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,54),
(358,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,54),
(359,'Camión grúa','Camiones grúa a disposición de la empresa',2,54),
(360,'Camión bombero','Camiones bombero a disposición de la empresa',2,54),
(361,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,59),
(362,'Cortador anular','Cortadores anulares a disposición de la empresa',4,59),
(363,'Segueta','Seguetas a disposición de la empresa',4,59),
(364,'Sierra circular','Sierras circulares a disposición de la empresa',4,59),
(365,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,59),
(366,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,59),
(367,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,59),
(368,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,59),
(369,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,59),
(370,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,59),
(371,'Excavadora','Excavadoras a disposición de la empresa',2,59),
(372,'Perforadora','Perforadoras a disposición de la empresa',2,59),
(373,'Rodillo','Rodillos a disposición de la empresa',2,59),
(374,'Tractor oruga','Tractores oruga a disposición de la empresa',2,59),
(375,'Camioneta','Camionetas a disposición de la empresa',2,59),
(376,'Bus','Buses a disposición de la empresa',2,59),
(377,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,59),
(378,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,59),
(379,'Camión grúa','Camiones grúa a disposición de la empresa',2,59),
(380,'Camión bombero','Camiones bombero a disposición de la empresa',2,59),
(381,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,60),
(382,'Cortador anular','Cortadores anulares a disposición de la empresa',4,60),
(383,'Segueta','Seguetas a disposición de la empresa',4,60),
(384,'Sierra circular','Sierras circulares a disposición de la empresa',4,60),
(385,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,60),
(386,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,60),
(387,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,60),
(388,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,60),
(389,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,60),
(390,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,60),
(391,'Excavadora','Excavadoras a disposición de la empresa',2,60),
(392,'Perforadora','Perforadoras a disposición de la empresa',2,60),
(393,'Rodillo','Rodillos a disposición de la empresa',2,60),
(394,'Tractor oruga','Tractores oruga a disposición de la empresa',2,60),
(395,'Camioneta','Camionetas a disposición de la empresa',2,60),
(396,'Bus','Buses a disposición de la empresa',2,60),
(397,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,60),
(398,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,60),
(399,'Camión grúa','Camiones grúa a disposición de la empresa',2,60),
(400,'Camión bombero','Camiones bombero a disposición de la empresa',2,60),
(401,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,65),
(402,'Cortador anular','Cortadores anulares a disposición de la empresa',4,65),
(403,'Segueta','Seguetas a disposición de la empresa',4,65),
(404,'Sierra circular','Sierras circulares a disposición de la empresa',4,65),
(405,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,65),
(406,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,65),
(407,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,65),
(408,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,65),
(409,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,65),
(410,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,65),
(411,'Excavadora','Excavadoras a disposición de la empresa',2,65),
(412,'Perforadora','Perforadoras a disposición de la empresa',2,65),
(413,'Rodillo','Rodillos a disposición de la empresa',2,65),
(414,'Tractor oruga','Tractores oruga a disposición de la empresa',2,65),
(415,'Camioneta','Camionetas a disposición de la empresa',2,65),
(416,'Bus','Buses a disposición de la empresa',2,65),
(417,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,65),
(418,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,65),
(419,'Camión grúa','Camiones grúa a disposición de la empresa',2,65),
(420,'Camión bombero','Camiones bombero a disposición de la empresa',2,65),
(421,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,66),
(422,'Cortador anular','Cortadores anulares a disposición de la empresa',4,66),
(423,'Segueta','Seguetas a disposición de la empresa',4,66),
(424,'Sierra circular','Sierras circulares a disposición de la empresa',4,66),
(425,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,66),
(426,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,66),
(427,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,66),
(428,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,66),
(429,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,66),
(430,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,66),
(431,'Excavadora','Excavadoras a disposición de la empresa',2,66),
(432,'Perforadora','Perforadoras a disposición de la empresa',2,66),
(433,'Rodillo','Rodillos a disposición de la empresa',2,66),
(434,'Tractor oruga','Tractores oruga a disposición de la empresa',2,66),
(435,'Camioneta','Camionetas a disposición de la empresa',2,66),
(436,'Bus','Buses a disposición de la empresa',2,66),
(437,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,66),
(438,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,66),
(439,'Camión grúa','Camiones grúa a disposición de la empresa',2,66),
(440,'Camión bombero','Camiones bombero a disposición de la empresa',2,66),
(441,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,71),
(442,'Cortador anular','Cortadores anulares a disposición de la empresa',4,71),
(443,'Segueta','Seguetas a disposición de la empresa',4,71),
(444,'Sierra circular','Sierras circulares a disposición de la empresa',4,71),
(445,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,71),
(446,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,71),
(447,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,71),
(448,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,71),
(449,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,71),
(450,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,71),
(451,'Excavadora','Excavadoras a disposición de la empresa',2,71),
(452,'Perforadora','Perforadoras a disposición de la empresa',2,71),
(453,'Rodillo','Rodillos a disposición de la empresa',2,71),
(454,'Tractor oruga','Tractores oruga a disposición de la empresa',2,71),
(455,'Camioneta','Camionetas a disposición de la empresa',2,71),
(456,'Bus','Buses a disposición de la empresa',2,71),
(457,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,71),
(458,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,71),
(459,'Camión grúa','Camiones grúa a disposición de la empresa',2,71),
(460,'Camión bombero','Camiones bombero a disposición de la empresa',2,71),
(461,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,72),
(462,'Cortador anular','Cortadores anulares a disposición de la empresa',4,72),
(463,'Segueta','Seguetas a disposición de la empresa',4,72),
(464,'Sierra circular','Sierras circulares a disposición de la empresa',4,72),
(465,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,72),
(466,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,72),
(467,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,72),
(468,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,72),
(469,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,72),
(470,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,72),
(471,'Excavadora','Excavadoras a disposición de la empresa',2,72),
(472,'Perforadora','Perforadoras a disposición de la empresa',2,72),
(473,'Rodillo','Rodillos a disposición de la empresa',2,72),
(474,'Tractor oruga','Tractores oruga a disposición de la empresa',2,72),
(475,'Camioneta','Camionetas a disposición de la empresa',2,72),
(476,'Bus','Buses a disposición de la empresa',2,72),
(477,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,72),
(478,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,72),
(479,'Camión grúa','Camiones grúa a disposición de la empresa',2,72),
(480,'Camión bombero','Camiones bombero a disposición de la empresa',2,72),
(481,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,77),
(482,'Cortador anular','Cortadores anulares a disposición de la empresa',4,77),
(483,'Segueta','Seguetas a disposición de la empresa',4,77),
(484,'Sierra circular','Sierras circulares a disposición de la empresa',4,77),
(485,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,77),
(486,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,77),
(487,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,77),
(488,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,77),
(489,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,77),
(490,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,77),
(491,'Excavadora','Excavadoras a disposición de la empresa',2,77),
(492,'Perforadora','Perforadoras a disposición de la empresa',2,77),
(493,'Rodillo','Rodillos a disposición de la empresa',2,77),
(494,'Tractor oruga','Tractores oruga a disposición de la empresa',2,77),
(495,'Camioneta','Camionetas a disposición de la empresa',2,77),
(496,'Bus','Buses a disposición de la empresa',2,77),
(497,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,77),
(498,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,77),
(499,'Camión grúa','Camiones grúa a disposición de la empresa',2,77),
(500,'Camión bombero','Camiones bombero a disposición de la empresa',2,77),
(501,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,78),
(502,'Cortador anular','Cortadores anulares a disposición de la empresa',4,78),
(503,'Segueta','Seguetas a disposición de la empresa',4,78),
(504,'Sierra circular','Sierras circulares a disposición de la empresa',4,78),
(505,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,78),
(506,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,78),
(507,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,78),
(508,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,78),
(509,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,78),
(510,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,78),
(511,'Excavadora','Excavadoras a disposición de la empresa',2,78),
(512,'Perforadora','Perforadoras a disposición de la empresa',2,78),
(513,'Rodillo','Rodillos a disposición de la empresa',2,78),
(514,'Tractor oruga','Tractores oruga a disposición de la empresa',2,78),
(515,'Camioneta','Camionetas a disposición de la empresa',2,78),
(516,'Bus','Buses a disposición de la empresa',2,78),
(517,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,78),
(518,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,78),
(519,'Camión grúa','Camiones grúa a disposición de la empresa',2,78),
(520,'Camión bombero','Camiones bombero a disposición de la empresa',2,78),
(521,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,83),
(522,'Cortador anular','Cortadores anulares a disposición de la empresa',4,83),
(523,'Segueta','Seguetas a disposición de la empresa',4,83),
(524,'Sierra circular','Sierras circulares a disposición de la empresa',4,83),
(525,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,83),
(526,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,83),
(527,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,83),
(528,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,83),
(529,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,83),
(530,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,83),
(531,'Excavadora','Excavadoras a disposición de la empresa',2,83),
(532,'Perforadora','Perforadoras a disposición de la empresa',2,83),
(533,'Rodillo','Rodillos a disposición de la empresa',2,83),
(534,'Tractor oruga','Tractores oruga a disposición de la empresa',2,83),
(535,'Camioneta','Camionetas a disposición de la empresa',2,83),
(536,'Bus','Buses a disposición de la empresa',2,83),
(537,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,83),
(538,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,83),
(539,'Camión grúa','Camiones grúa a disposición de la empresa',2,83),
(540,'Camión bombero','Camiones bombero a disposición de la empresa',2,83),
(541,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,84),
(542,'Cortador anular','Cortadores anulares a disposición de la empresa',4,84),
(543,'Segueta','Seguetas a disposición de la empresa',4,84),
(544,'Sierra circular','Sierras circulares a disposición de la empresa',4,84),
(545,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,84),
(546,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,84),
(547,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,84),
(548,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,84),
(549,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,84),
(550,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,84),
(551,'Excavadora','Excavadoras a disposición de la empresa',2,84),
(552,'Perforadora','Perforadoras a disposición de la empresa',2,84),
(553,'Rodillo','Rodillos a disposición de la empresa',2,84),
(554,'Tractor oruga','Tractores oruga a disposición de la empresa',2,84),
(555,'Camioneta','Camionetas a disposición de la empresa',2,84),
(556,'Bus','Buses a disposición de la empresa',2,84),
(557,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,84),
(558,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,84),
(559,'Camión grúa','Camiones grúa a disposición de la empresa',2,84),
(560,'Camión bombero','Camiones bombero a disposición de la empresa',2,84),
(561,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,89),
(562,'Cortador anular','Cortadores anulares a disposición de la empresa',4,89),
(563,'Segueta','Seguetas a disposición de la empresa',4,89),
(564,'Sierra circular','Sierras circulares a disposición de la empresa',4,89),
(565,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,89),
(566,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,89),
(567,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,89),
(568,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,89),
(569,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,89),
(570,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,89),
(571,'Excavadora','Excavadoras a disposición de la empresa',2,89),
(572,'Perforadora','Perforadoras a disposición de la empresa',2,89),
(573,'Rodillo','Rodillos a disposición de la empresa',2,89),
(574,'Tractor oruga','Tractores oruga a disposición de la empresa',2,89),
(575,'Camioneta','Camionetas a disposición de la empresa',2,89),
(576,'Bus','Buses a disposición de la empresa',2,89),
(577,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,89),
(578,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,89),
(579,'Camión grúa','Camiones grúa a disposición de la empresa',2,89),
(580,'Camión bombero','Camiones bombero a disposición de la empresa',2,89),
(581,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,90),
(582,'Cortador anular','Cortadores anulares a disposición de la empresa',4,90),
(583,'Segueta','Seguetas a disposición de la empresa',4,90),
(584,'Sierra circular','Sierras circulares a disposición de la empresa',4,90),
(585,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,90),
(586,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,90),
(587,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,90),
(588,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,90),
(589,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,90),
(590,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,90),
(591,'Excavadora','Excavadoras a disposición de la empresa',2,90),
(592,'Perforadora','Perforadoras a disposición de la empresa',2,90),
(593,'Rodillo','Rodillos a disposición de la empresa',2,90),
(594,'Tractor oruga','Tractores oruga a disposición de la empresa',2,90),
(595,'Camioneta','Camionetas a disposición de la empresa',2,90),
(596,'Bus','Buses a disposición de la empresa',2,90),
(597,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,90),
(598,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,90),
(599,'Camión grúa','Camiones grúa a disposición de la empresa',2,90),
(600,'Camión bombero','Camiones bombero a disposición de la empresa',2,90),
(601,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,95),
(602,'Cortador anular','Cortadores anulares a disposición de la empresa',4,95),
(603,'Segueta','Seguetas a disposición de la empresa',4,95),
(604,'Sierra circular','Sierras circulares a disposición de la empresa',4,95),
(605,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,95),
(606,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,95),
(607,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,95),
(608,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,95),
(609,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,95),
(610,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,95),
(611,'Excavadora','Excavadoras a disposición de la empresa',2,95),
(612,'Perforadora','Perforadoras a disposición de la empresa',2,95),
(613,'Rodillo','Rodillos a disposición de la empresa',2,95),
(614,'Tractor oruga','Tractores oruga a disposición de la empresa',2,95),
(615,'Camioneta','Camionetas a disposición de la empresa',2,95),
(616,'Bus','Buses a disposición de la empresa',2,95),
(617,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,95),
(618,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,95),
(619,'Camión grúa','Camiones grúa a disposición de la empresa',2,95),
(620,'Camión bombero','Camiones bombero a disposición de la empresa',2,95),
(621,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,96),
(622,'Cortador anular','Cortadores anulares a disposición de la empresa',4,96),
(623,'Segueta','Seguetas a disposición de la empresa',4,96),
(624,'Sierra circular','Sierras circulares a disposición de la empresa',4,96),
(625,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,96),
(626,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,96),
(627,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,96),
(628,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,96),
(629,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,96),
(630,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,96),
(631,'Excavadora','Excavadoras a disposición de la empresa',2,96),
(632,'Perforadora','Perforadoras a disposición de la empresa',2,96),
(633,'Rodillo','Rodillos a disposición de la empresa',2,96),
(634,'Tractor oruga','Tractores oruga a disposición de la empresa',2,96),
(635,'Camioneta','Camionetas a disposición de la empresa',2,96),
(636,'Bus','Buses a disposición de la empresa',2,96),
(637,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,96),
(638,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,96),
(639,'Camión grúa','Camiones grúa a disposición de la empresa',2,96),
(640,'Camión bombero','Camiones bombero a disposición de la empresa',2,96),
(641,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,101),
(642,'Cortador anular','Cortadores anulares a disposición de la empresa',4,101),
(643,'Segueta','Seguetas a disposición de la empresa',4,101),
(644,'Sierra circular','Sierras circulares a disposición de la empresa',4,101),
(645,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,101),
(646,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,101),
(647,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,101),
(648,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,101),
(649,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,101),
(650,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,101),
(651,'Excavadora','Excavadoras a disposición de la empresa',2,101),
(652,'Perforadora','Perforadoras a disposición de la empresa',2,101),
(653,'Rodillo','Rodillos a disposición de la empresa',2,101),
(654,'Tractor oruga','Tractores oruga a disposición de la empresa',2,101),
(655,'Camioneta','Camionetas a disposición de la empresa',2,101),
(656,'Bus','Buses a disposición de la empresa',2,101),
(657,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,101),
(658,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,101),
(659,'Camión grúa','Camiones grúa a disposición de la empresa',2,101),
(660,'Camión bombero','Camiones bombero a disposición de la empresa',2,101),
(661,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,102),
(662,'Cortador anular','Cortadores anulares a disposición de la empresa',4,102),
(663,'Segueta','Seguetas a disposición de la empresa',4,102),
(664,'Sierra circular','Sierras circulares a disposición de la empresa',4,102),
(665,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,102),
(666,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,102),
(667,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,102),
(668,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,102),
(669,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,102),
(670,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,102),
(671,'Excavadora','Excavadoras a disposición de la empresa',2,102),
(672,'Perforadora','Perforadoras a disposición de la empresa',2,102),
(673,'Rodillo','Rodillos a disposición de la empresa',2,102),
(674,'Tractor oruga','Tractores oruga a disposición de la empresa',2,102),
(675,'Camioneta','Camionetas a disposición de la empresa',2,102),
(676,'Bus','Buses a disposición de la empresa',2,102),
(677,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,102),
(678,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,102),
(679,'Camión grúa','Camiones grúa a disposición de la empresa',2,102),
(680,'Camión bombero','Camiones bombero a disposición de la empresa',2,102),
(681,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,107),
(682,'Cortador anular','Cortadores anulares a disposición de la empresa',4,107),
(683,'Segueta','Seguetas a disposición de la empresa',4,107),
(684,'Sierra circular','Sierras circulares a disposición de la empresa',4,107),
(685,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,107),
(686,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,107),
(687,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,107),
(688,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,107),
(689,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,107),
(690,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,107),
(691,'Excavadora','Excavadoras a disposición de la empresa',2,107),
(692,'Perforadora','Perforadoras a disposición de la empresa',2,107),
(693,'Rodillo','Rodillos a disposición de la empresa',2,107),
(694,'Tractor oruga','Tractores oruga a disposición de la empresa',2,107),
(695,'Camioneta','Camionetas a disposición de la empresa',2,107),
(696,'Bus','Buses a disposición de la empresa',2,107),
(697,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,107),
(698,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,107),
(699,'Camión grúa','Camiones grúa a disposición de la empresa',2,107),
(700,'Camión bombero','Camiones bombero a disposición de la empresa',2,107),
(701,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,108),
(702,'Cortador anular','Cortadores anulares a disposición de la empresa',4,108),
(703,'Segueta','Seguetas a disposición de la empresa',4,108),
(704,'Sierra circular','Sierras circulares a disposición de la empresa',4,108),
(705,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,108),
(706,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,108),
(707,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,108),
(708,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,108),
(709,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,108),
(710,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,108),
(711,'Excavadora','Excavadoras a disposición de la empresa',2,108),
(712,'Perforadora','Perforadoras a disposición de la empresa',2,108),
(713,'Rodillo','Rodillos a disposición de la empresa',2,108),
(714,'Tractor oruga','Tractores oruga a disposición de la empresa',2,108),
(715,'Camioneta','Camionetas a disposición de la empresa',2,108),
(716,'Bus','Buses a disposición de la empresa',2,108),
(717,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,108),
(718,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,108),
(719,'Camión grúa','Camiones grúa a disposición de la empresa',2,108),
(720,'Camión bombero','Camiones bombero a disposición de la empresa',2,108),
(721,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,113),
(722,'Cortador anular','Cortadores anulares a disposición de la empresa',4,113),
(723,'Segueta','Seguetas a disposición de la empresa',4,113),
(724,'Sierra circular','Sierras circulares a disposición de la empresa',4,113),
(725,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,113),
(726,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,113),
(727,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,113),
(728,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,113),
(729,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,113),
(730,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,113),
(731,'Excavadora','Excavadoras a disposición de la empresa',2,113),
(732,'Perforadora','Perforadoras a disposición de la empresa',2,113),
(733,'Rodillo','Rodillos a disposición de la empresa',2,113),
(734,'Tractor oruga','Tractores oruga a disposición de la empresa',2,113),
(735,'Camioneta','Camionetas a disposición de la empresa',2,113),
(736,'Bus','Buses a disposición de la empresa',2,113),
(737,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,113),
(738,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,113),
(739,'Camión grúa','Camiones grúa a disposición de la empresa',2,113),
(740,'Camión bombero','Camiones bombero a disposición de la empresa',2,113),
(741,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,114),
(742,'Cortador anular','Cortadores anulares a disposición de la empresa',4,114),
(743,'Segueta','Seguetas a disposición de la empresa',4,114),
(744,'Sierra circular','Sierras circulares a disposición de la empresa',4,114),
(745,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,114),
(746,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,114),
(747,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,114),
(748,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,114),
(749,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,114),
(750,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,114),
(751,'Excavadora','Excavadoras a disposición de la empresa',2,114),
(752,'Perforadora','Perforadoras a disposición de la empresa',2,114),
(753,'Rodillo','Rodillos a disposición de la empresa',2,114),
(754,'Tractor oruga','Tractores oruga a disposición de la empresa',2,114),
(755,'Camioneta','Camionetas a disposición de la empresa',2,114),
(756,'Bus','Buses a disposición de la empresa',2,114),
(757,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,114),
(758,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,114),
(759,'Camión grúa','Camiones grúa a disposición de la empresa',2,114),
(760,'Camión bombero','Camiones bombero a disposición de la empresa',2,114),
(761,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,119),
(762,'Cortador anular','Cortadores anulares a disposición de la empresa',4,119),
(763,'Segueta','Seguetas a disposición de la empresa',4,119),
(764,'Sierra circular','Sierras circulares a disposición de la empresa',4,119),
(765,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,119),
(766,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,119),
(767,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,119),
(768,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,119),
(769,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,119),
(770,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,119),
(771,'Excavadora','Excavadoras a disposición de la empresa',2,119),
(772,'Perforadora','Perforadoras a disposición de la empresa',2,119),
(773,'Rodillo','Rodillos a disposición de la empresa',2,119),
(774,'Tractor oruga','Tractores oruga a disposición de la empresa',2,119),
(775,'Camioneta','Camionetas a disposición de la empresa',2,119),
(776,'Bus','Buses a disposición de la empresa',2,119),
(777,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,119),
(778,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,119),
(779,'Camión grúa','Camiones grúa a disposición de la empresa',2,119),
(780,'Camión bombero','Camiones bombero a disposición de la empresa',2,119),
(781,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,120),
(782,'Cortador anular','Cortadores anulares a disposición de la empresa',4,120),
(783,'Segueta','Seguetas a disposición de la empresa',4,120),
(784,'Sierra circular','Sierras circulares a disposición de la empresa',4,120),
(785,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,120),
(786,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,120),
(787,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,120),
(788,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,120),
(789,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,120),
(790,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,120),
(791,'Excavadora','Excavadoras a disposición de la empresa',2,120),
(792,'Perforadora','Perforadoras a disposición de la empresa',2,120),
(793,'Rodillo','Rodillos a disposición de la empresa',2,120),
(794,'Tractor oruga','Tractores oruga a disposición de la empresa',2,120),
(795,'Camioneta','Camionetas a disposición de la empresa',2,120),
(796,'Bus','Buses a disposición de la empresa',2,120),
(797,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,120),
(798,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,120),
(799,'Camión grúa','Camiones grúa a disposición de la empresa',2,120),
(800,'Camión bombero','Camiones bombero a disposición de la empresa',2,120),
(801,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,125),
(802,'Cortador anular','Cortadores anulares a disposición de la empresa',4,125),
(803,'Segueta','Seguetas a disposición de la empresa',4,125),
(804,'Sierra circular','Sierras circulares a disposición de la empresa',4,125),
(805,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,125),
(806,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,125),
(807,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,125),
(808,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,125),
(809,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,125),
(810,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,125),
(811,'Excavadora','Excavadoras a disposición de la empresa',2,125),
(812,'Perforadora','Perforadoras a disposición de la empresa',2,125),
(813,'Rodillo','Rodillos a disposición de la empresa',2,125),
(814,'Tractor oruga','Tractores oruga a disposición de la empresa',2,125),
(815,'Camioneta','Camionetas a disposición de la empresa',2,125),
(816,'Bus','Buses a disposición de la empresa',2,125),
(817,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,125),
(818,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,125),
(819,'Camión grúa','Camiones grúa a disposición de la empresa',2,125),
(820,'Camión bombero','Camiones bombero a disposición de la empresa',2,125),
(821,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,126),
(822,'Cortador anular','Cortadores anulares a disposición de la empresa',4,126),
(823,'Segueta','Seguetas a disposición de la empresa',4,126),
(824,'Sierra circular','Sierras circulares a disposición de la empresa',4,126),
(825,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,126),
(826,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,126),
(827,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,126),
(828,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,126),
(829,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,126),
(830,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,126),
(831,'Excavadora','Excavadoras a disposición de la empresa',2,126),
(832,'Perforadora','Perforadoras a disposición de la empresa',2,126),
(833,'Rodillo','Rodillos a disposición de la empresa',2,126),
(834,'Tractor oruga','Tractores oruga a disposición de la empresa',2,126),
(835,'Camioneta','Camionetas a disposición de la empresa',2,126),
(836,'Bus','Buses a disposición de la empresa',2,126),
(837,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,126),
(838,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,126),
(839,'Camión grúa','Camiones grúa a disposición de la empresa',2,126),
(840,'Camión bombero','Camiones bombero a disposición de la empresa',2,126),
(841,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,131),
(842,'Cortador anular','Cortadores anulares a disposición de la empresa',4,131),
(843,'Segueta','Seguetas a disposición de la empresa',4,131),
(844,'Sierra circular','Sierras circulares a disposición de la empresa',4,131),
(845,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,131),
(846,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,131),
(847,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,131),
(848,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,131),
(849,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,131),
(850,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,131),
(851,'Excavadora','Excavadoras a disposición de la empresa',2,131),
(852,'Perforadora','Perforadoras a disposición de la empresa',2,131),
(853,'Rodillo','Rodillos a disposición de la empresa',2,131),
(854,'Tractor oruga','Tractores oruga a disposición de la empresa',2,131),
(855,'Camioneta','Camionetas a disposición de la empresa',2,131),
(856,'Bus','Buses a disposición de la empresa',2,131),
(857,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,131),
(858,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,131),
(859,'Camión grúa','Camiones grúa a disposición de la empresa',2,131),
(860,'Camión bombero','Camiones bombero a disposición de la empresa',2,131),
(861,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,132),
(862,'Cortador anular','Cortadores anulares a disposición de la empresa',4,132),
(863,'Segueta','Seguetas a disposición de la empresa',4,132),
(864,'Sierra circular','Sierras circulares a disposición de la empresa',4,132),
(865,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,132),
(866,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,132),
(867,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,132),
(868,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,132),
(869,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,132),
(870,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,132),
(871,'Excavadora','Excavadoras a disposición de la empresa',2,132),
(872,'Perforadora','Perforadoras a disposición de la empresa',2,132),
(873,'Rodillo','Rodillos a disposición de la empresa',2,132),
(874,'Tractor oruga','Tractores oruga a disposición de la empresa',2,132),
(875,'Camioneta','Camionetas a disposición de la empresa',2,132),
(876,'Bus','Buses a disposición de la empresa',2,132),
(877,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,132),
(878,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,132),
(879,'Camión grúa','Camiones grúa a disposición de la empresa',2,132),
(880,'Camión bombero','Camiones bombero a disposición de la empresa',2,132),
(881,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,137),
(882,'Cortador anular','Cortadores anulares a disposición de la empresa',4,137),
(883,'Segueta','Seguetas a disposición de la empresa',4,137),
(884,'Sierra circular','Sierras circulares a disposición de la empresa',4,137),
(885,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,137),
(886,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,137),
(887,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,137),
(888,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,137),
(889,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,137),
(890,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,137),
(891,'Excavadora','Excavadoras a disposición de la empresa',2,137),
(892,'Perforadora','Perforadoras a disposición de la empresa',2,137),
(893,'Rodillo','Rodillos a disposición de la empresa',2,137),
(894,'Tractor oruga','Tractores oruga a disposición de la empresa',2,137),
(895,'Camioneta','Camionetas a disposición de la empresa',2,137),
(896,'Bus','Buses a disposición de la empresa',2,137),
(897,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,137),
(898,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,137),
(899,'Camión grúa','Camiones grúa a disposición de la empresa',2,137),
(900,'Camión bombero','Camiones bombero a disposición de la empresa',2,137),
(901,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,138),
(902,'Cortador anular','Cortadores anulares a disposición de la empresa',4,138),
(903,'Segueta','Seguetas a disposición de la empresa',4,138),
(904,'Sierra circular','Sierras circulares a disposición de la empresa',4,138),
(905,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,138),
(906,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,138),
(907,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,138),
(908,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,138),
(909,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,138),
(910,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,138),
(911,'Excavadora','Excavadoras a disposición de la empresa',2,138),
(912,'Perforadora','Perforadoras a disposición de la empresa',2,138),
(913,'Rodillo','Rodillos a disposición de la empresa',2,138),
(914,'Tractor oruga','Tractores oruga a disposición de la empresa',2,138),
(915,'Camioneta','Camionetas a disposición de la empresa',2,138),
(916,'Bus','Buses a disposición de la empresa',2,138),
(917,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,138),
(918,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,138),
(919,'Camión grúa','Camiones grúa a disposición de la empresa',2,138),
(920,'Camión bombero','Camiones bombero a disposición de la empresa',2,138),
(921,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,143),
(922,'Cortador anular','Cortadores anulares a disposición de la empresa',4,143),
(923,'Segueta','Seguetas a disposición de la empresa',4,143),
(924,'Sierra circular','Sierras circulares a disposición de la empresa',4,143),
(925,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,143),
(926,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,143),
(927,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,143),
(928,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,143),
(929,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,143),
(930,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,143),
(931,'Excavadora','Excavadoras a disposición de la empresa',2,143),
(932,'Perforadora','Perforadoras a disposición de la empresa',2,143),
(933,'Rodillo','Rodillos a disposición de la empresa',2,143),
(934,'Tractor oruga','Tractores oruga a disposición de la empresa',2,143),
(935,'Camioneta','Camionetas a disposición de la empresa',2,143),
(936,'Bus','Buses a disposición de la empresa',2,143),
(937,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,143),
(938,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,143),
(939,'Camión grúa','Camiones grúa a disposición de la empresa',2,143),
(940,'Camión bombero','Camiones bombero a disposición de la empresa',2,143),
(941,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,144),
(942,'Cortador anular','Cortadores anulares a disposición de la empresa',4,144),
(943,'Segueta','Seguetas a disposición de la empresa',4,144),
(944,'Sierra circular','Sierras circulares a disposición de la empresa',4,144),
(945,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,144),
(946,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,144),
(947,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,144),
(948,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,144),
(949,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,144),
(950,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,144),
(951,'Excavadora','Excavadoras a disposición de la empresa',2,144),
(952,'Perforadora','Perforadoras a disposición de la empresa',2,144),
(953,'Rodillo','Rodillos a disposición de la empresa',2,144),
(954,'Tractor oruga','Tractores oruga a disposición de la empresa',2,144),
(955,'Camioneta','Camionetas a disposición de la empresa',2,144),
(956,'Bus','Buses a disposición de la empresa',2,144),
(957,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,144),
(958,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,144),
(959,'Camión grúa','Camiones grúa a disposición de la empresa',2,144),
(960,'Camión bombero','Camiones bombero a disposición de la empresa',2,144),
(961,'Taladro neumático','Taladros neumáticos a disposición de la empresa',4,NULL),
(962,'Cortador anular','Cortadores anulares a disposición de la empresa',4,NULL),
(963,'Segueta','Seguetas a disposición de la empresa',4,NULL),
(964,'Sierra circular','Sierras circulares a disposición de la empresa',4,NULL),
(965,'Raspador de cincel','Raspadores de cincel a disposición de la empresa',4,NULL),
(966,'Ventilador axial','Ventiladores axiales a disposición de la empresa',4,NULL),
(967,'Circulador de aire','Circuladores de aire a disposición de la empresa',4,NULL),
(968,'Mezcladora neumática','Mezcladoras neumáticas a disposición de la empresa',4,NULL),
(969,'Aspiradora neumática','Aspiradoras neumáticas a disposición de la empresa',4,NULL),
(970,'Unidad de potancia hidráulica','Unidades de potencia hidráulicas a disposición de la empresa',4,NULL),
(971,'Excavadora','Excavadoras a disposición de la empresa',2,NULL),
(972,'Perforadora','Perforadoras a disposición de la empresa',2,NULL),
(973,'Rodillo','Rodillos a disposición de la empresa',2,NULL),
(974,'Tractor oruga','Tractores oruga a disposición de la empresa',2,NULL),
(975,'Camioneta','Camionetas a disposición de la empresa',2,NULL),
(976,'Bus','Buses a disposición de la empresa',2,NULL),
(977,'Camión cisterna','Camiones cisterna a disposición de la empresa',2,NULL),
(978,'Camión plataforma','Camiones plataforma a disposición de la empresa',2,NULL),
(979,'Camión grúa','Camiones grúa a disposición de la empresa',2,NULL),
(980,'Camión bombero','Camiones bombero a disposición de la empresa',2,NULL);