CREATE TABLE PUBLIC.PX_PROYECTO(
	ID					NUMERIC(8)		NOT NULL UNIQUE,
	NOMBRE				VARCHAR(30)		NOT NULL,
	DESCRIPCION			TEXT			NOT NULL,
	FECHA_INICIO		DATE			NOT NULL,
	FECHA_FIN_EST		DATE			NOT NULL,
	FECHA_FIN			DATE,
	APROBADO			BOOLEAN			NOT NULL DEFAULT FALSE,
	YACIMIENTO_CODIGO	NUMERIC(6)		NOT NULL,
	
	CONSTRAINT PK_PROYECTO				PRIMARY KEY(ID),
	CONSTRAINT FK_PROYECTO_YACIMIENTO	FOREIGN KEY(YACIMIENTO_CODIGO) REFERENCES PUBLIC.MH_YACIMIENTO(ID)
);