CREATE TABLE PUBLIC.EX_PERMISO(
	USUARIO_CI		VARCHAR(10)	NOT NULL,
	PRIVILEGIO_ID	NUMERIC(2)	NOT NULL,
	ACCION			CHAR(1)		NOT NULL,

	CONSTRAINT PK_PERMISO				PRIMARY KEY(USUARIO_CI, PRIVILEGIO_ID, ACCION),
	CONSTRAINT FK_PERMISO_USUARIO		FOREIGN KEY(USUARIO_CI)		REFERENCES PUBLIC.EX_USUARIO(EMPLEADO_CI),
	CONSTRAINT FK_PERMISO_PRIVILEGIO	FOREIGN KEY(PRIVILEGIO_ID)	REFERENCES PUBLIC.EL_PRIVILEGIO(ID),
	CONSTRAINT CK_PERMISO_ACCION		CHECK(ACCION IN ('L', 'E'))
);