CREATE TABLE PUBLIC.SX_PAGO(
    TARJETA_NUMERO			NUMERIC(18)		NOT NULL,
    FACTURA_NUMERO			NUMERIC(8)		NOT NULL,
    NUMERO					NUMERIC(3)		NOT NULL,
    CANTIDAD	            NUMERIC(10,2)	NOT NULL,
    FECHA_REGISTRO			DATE			NOT NULL,
    
    CONSTRAINT PK_PAGO PRIMARY KEY(TARJETA_NUMERO, FACTURA_NUMERO, NUMERO),
    CONSTRAINT FK_PAGO_TARJETA FOREIGN KEY(TARJETA_NUMERO) REFERENCES PUBLIC.CX_TARJETA(NUMERO),
    CONSTRAINT FK_PAGO_FACTURA FOREIGN KEY(FACTURA_NUMERO) REFERENCES PUBLIC.SC_FACTURA(NUMERO)
);