CREATE OR REPLACE PROCEDURE PUBLIC.EP_CREAR_EMPLEADO(
	p_ci VARCHAR(10),
	p_p_nombre VARCHAR(16),
	p_s_nombre VARCHAR(16),
	p_p_apellido VARCHAR(20),
	p_s_apellido VARCHAR(20),
	p_sexo CHAR(1),
	p_salario NUMERIC(6,2),
	p_rol NUMERIC(2),
	p_fecha_nacimiento DATE,
	p_fecha_ingreso DATE DEFAULT CURRENT_DATE
)
LANGUAGE plpgsql
AS $$
DECLARE
	USERNAME VARCHAR(25);
	EXISTE NUMERIC(1);
	CONTADOR NUMERIC(2);
	DEPT_ROL VARCHAR(30);
BEGIN
	INSERT INTO PUBLIC.EX_EMPLEADO(CI, P_NOMBRE, S_NOMBRE, P_APELLIDO, S_APELLIDO, FECHA_NACIMIENTO, FECHA_INGRESO, SEXO, SALARIO, ROL_CODIGO)
	VALUES(p_ci, p_p_nombre, p_s_nombre, p_p_apellido, p_s_apellido, p_fecha_nacimiento, p_fecha_ingreso, p_sexo, p_salario, p_rol);
	
	INSERT INTO PUBLIC.EX_JORNADA(EMPLEADO_CI, HORARIO_CODIGO)
	SELECT p_ci, CODIGO FROM EX_HORARIO;
	
	USERNAME := SUBSTRING(p_p_nombre, 1, 1)||SUBSTRING(COALESCE(p_s_nombre,''), 1, 1)||p_p_apellido;
	CONTADOR := 0;
	
	LOOP
		SELECT COUNT(*)
		INTO EXISTE
		FROM PG_ROLES
		WHERE ROLNAME = USERNAME;

		IF EXISTE > 0 THEN
			CONTADOR := CONTADOR + 1;
			USERNAME := USERNAME||TO_CHAR(CONTADOR, '99');
		END IF;
		
		EXIT WHEN EXISTE = 0;
	END LOOP;
	
	SELECT DEPT.NOMBRE
	INTO DEPT_ROL
	FROM EL_DEPARTAMENTO DEPT
	JOIN EL_ROL ON (EL_ROL.DEPARTAMENTO_NUMERO = DEPT.NUMERO)
	WHERE EL_ROL.CODIGO = p_rol;
	
	EXECUTE format('DROP USER IF EXISTS %s', USERNAME);
	EXECUTE format('CREATE USER %s PASSWORD %L IN ROLE %s', USERNAME, p_ci, DEPT_ROL);
END;
$$