CREATE TABLE PUBLIC.CX_EMPRESA(
	RIF					NUMERIC(10)		NOT NULL UNIQUE,
	NOMBRE				VARCHAR(30)		NOT NULL,
	FECHA_FUNDACION		DATE			NOT NULL,
	DIRECCION			VARCHAR(60)		NOT NULL,
	LUGAR_ID			NUMERIC(6)		NOT NULL,
	
	CONSTRAINT PK_EMPRESA		PRIMARY KEY(RIF),
	CONSTRAINT FK_EMPRESA_LUGAR	FOREIGN KEY(LUGAR_ID) REFERENCES PUBLIC.GL_LUGAR(ID)
);