CREATE TABLE PUBLIC.GX_TELEFONO(
	PREFIJO		NUMERIC(3)	NOT NULL,
	COD_AREA	NUMERIC(3)	NOT NULL,
	NUMERO		NUMERIC(7)	NOT NULL,
	TIPO		CHAR(4)		NOT NULL,
	EMPLEADO_CI	VARCHAR(10),
	EMPRESA_RIF	NUMERIC(10),
	
	CONSTRAINT PK_TELEFONO 				PRIMARY KEY(PREFIJO, COD_AREA, NUMERO),
	CONSTRAINT FK_TELEFONO_EMPLEADO 	FOREIGN KEY(EMPLEADO_CI)	REFERENCES PUBLIC.EX_EMPLEADO(CI),
	CONSTRAINT FK_TELEFONO_EMPRESA		FOREIGN KEY(EMPRESA_RIF)	REFERENCES PUBLIC.CX_EMPRESA(RIF),
	CONSTRAINT CK_TELEFONO_TIPO			CHECK(TIPO IN ('PART', 'OFIC')),
	CONSTRAINT CK_TELEFONO_PROPIETARIO	CHECK((EMPLEADO_CI IS NOT NULL AND EMPRESA_RIF IS NULL) OR (EMPLEADO_CI IS NULL AND EMPRESA_RIF IS NOT NULL))
);