CREATE TABLE PUBLIC.CX_TARJETA(
	NUMERO				NUMERIC(18)		NOT NULL UNIQUE,
	PROPIETARIO			VARCHAR(60)		NOT NULL,
	FECHA_VENCIMIENTO	DATE			NOT NULL,
	METODO_PAGO_ID		NUMERIC(2)		NOT NULL,
	EMPRESA_RIF			NUMERIC(10)		NOT NULL,
	
	CONSTRAINT PK_TARJETA				PRIMARY KEY(NUMERO),
	CONSTRAINT FK_TARJETA_METODO_PAGO	FOREIGN KEY(METODO_PAGO_ID) REFERENCES PUBLIC.SL_METODO_PAGO(ID),
	CONSTRAINT FK_TARJETA_EMPRESA		FOREIGN KEY(EMPRESA_RIF) REFERENCES PUBLIC.CX_EMPRESA(RIF)
);