CREATE TABLE PUBLIC.PX_ADMINISTRADOR(
	PROYECTO_ID	NUMERIC(8)	NOT NULL,
	EMPLEADO_CI	VARCHAR(10)	NOT NULL,
	APROBADO	BOOLEAN		NOT NULL DEFAULT FALSE,
	ROL_CODIGO	NUMERIC(2)	NOT NULL,
	
	CONSTRAINT PK_ADMINISTRADOR 			PRIMARY KEY(PROYECTO_ID, EMPLEADO_CI),
	CONSTRAINT FK_ADMINISTRADOR_PROYECTO	FOREIGN KEY(PROYECTO_ID)	REFERENCES PUBLIC.PX_PROYECTO(ID),
	CONSTRAINT FK_ADMINISTRADOR_EMPLEADO	FOREIGN KEY(EMPLEADO_CI)	REFERENCES PUBLIC.EX_EMPLEADO(CI),
	CONSTRAINT FK_ADMINISTRADOR_ROL 		FOREIGN KEY(ROL_CODIGO)		REFERENCES PUBLIC.PL_ROL(CODIGO)
);