CREATE TABLE PUBLIC.EX_EMPLEADO(
	CI 		   			VARCHAR(10)		NOT NULL UNIQUE,
	P_NOMBRE   			VARCHAR(16)		NOT NULL,
	S_NOMBRE   			VARCHAR(16),
	P_APELLIDO 			VARCHAR(20)		NOT NULL,
	S_APELLIDO 			VARCHAR(20),
	FECHA_NACIMIENTO	DATE 			NOT NULL,
	FECHA_INGRESO		DATE			NOT NULL DEFAULT CURRENT_DATE,
	FECHA_SALIDA		DATE,
	SEXO				CHAR(1)	  		NOT NULL,
	SALARIO				NUMERIC(8,2)	NOT NULL,
	ESTATUS				CHAR(1)			NOT NULL,
	CARGO_CODIGO		NUMERIC(2)		NOT NULL,
	
	CONSTRAINT PK_EMPLEADO			PRIMARY KEY(CI),
	CONSTRAINT FK_EMPLEADO_CARGO	FOREIGN KEY(CARGO_CODIGO) REFERENCES PUBLIC.EL_CARGO(CODIGO),
	CONSTRAINT CK_EMPLEADO_SEXO		CHECK(SEXO IN ('M', 'F')),
	CONSTRAINT CK_EMPLEADO_ESTATUS	CHECK(ESTATUS IN ('D', 'O', 'I'))
);