CREATE TABLE PUBLIC.SC_FACTURA(
	NUMERO					NUMERIC(8)	NOT NULL UNIQUE,
	FECHA_REGISTRO			DATE		NOT NULL DEFAULT CURRENT_DATE,
	FECHA_CUMPLIMIENTO		DATE,
	ASIENTO_REF				NUMERIC(8)	NOT NULL,
	ASIENTO_CODIGO_CUENTA	NUMERIC(4)	NOT NULL,
	
	CONSTRAINT PK_C_FACTURA	PRIMARY KEY(NUMERO),
	CONSTRAINT FK_C_FACTURA_D_ASIENTO FOREIGN KEY(ASIENTO_REF, ASIENTO_CODIGO_CUENTA) REFERENCES PUBLIC.TD_ASIENTO(REF, CUENTA_CODIGO),
	CONSTRAINT UK_C_FACTURA_D_ASIENTO UNIQUE(ASIENTO_REF,ASIENTO_CODIGO_CUENTA)
);