CREATE TABLE PUBLIC.EX_JORNADA(
	EMPLEADO_CI		VARCHAR(10)	NOT NULL,
	HORARIO_CODIGO	NUMERIC(3)	NOT NULL,
	
	CONSTRAINT PK_JORNADA			PRIMARY KEY(EMPLEADO_CI, HORARIO_CODIGO),
	CONSTRAINT FK_JORNADA_EMPLEADO	FOREIGN KEY(EMPLEADO_CI)	REFERENCES PUBLIC.EX_EMPLEADO(CI),
	CONSTRAINT FK_JORNADA_HORARIO	FOREIGN KEY(HORARIO_CODIGO)	REFERENCES PUBLIC.EX_HORARIO(CODIGO)
);