CREATE TABLE PUBLIC.MH_POZO(
	YACIMIENTO_ID	NUMERIC(4)		NOT NULL,
	ID				NUMERIC(4)		NOT NULL,
	NOMBRE			VARCHAR(40)		NOT NULL,
	TIPO			VARCHAR(9)		NOT NULL,
	PROFUNDIDAD 	NUMERIC(10,3)	NOT NULL,
	AREA			NUMERIC(2)		NOT NULL,
	
	CONSTRAINT PK_POZO 			PRIMARY KEY(YACIMIENTO_ID, ID),
	CONSTRAINT CK_POZO_TIPO		CHECK(TIPO IN ('Vertical', 'Inclinado'))
);