CREATE TABLE PUBLIC.PX_USO(
	PROYECTO_ID			NUMERIC(8)	NOT NULL,
	FASE_ID				NUMERIC(2)	NOT NULL,
	ACTIVIDAD_NUMERO	NUMERIC(2)	NOT NULL,
	MAQUINARIA_ID		NUMERIC(4)	NOT NULL,
	CANTIDAD			VARCHAR(4)	NOT NULL,
	APROBADO			BOOLEAN		NOT NULL DEFAULT FALSE,
	
	CONSTRAINT PK_USO 			PRIMARY KEY(PROYECTO_ID, FASE_ID, ACTIVIDAD_NUMERO, MAQUINARIA_ID),
	CONSTRAINT FK_USO_ACTIVIDAD	FOREIGN KEY(PROYECTO_ID, FASE_ID, ACTIVIDAD_NUMERO)	REFERENCES PUBLIC.PX_ACTIVIDAD(PROYECTO_ID, FASE_ID, NUMERO),
	CONSTRAINT FK_USO_EMPLEADO	FOREIGN KEY(MAQUINARIA_ID)							REFERENCES PUBLIC.MX_MAQUINARIA(ID)
);