CREATE TABLE PUBLIC.SD_FACTURA(
	NUMERO			NUMERIC(8)		NOT NULL,
	MINERAL_CODIGO	NUMERIC(2)		NOT NULL,
	KG_COMERCIADOS	NUMERIC(10,3)	NOT NULL,
	PRECIO			NUMERIC(8,2)	NOT NULL,
	
	CONSTRAINT PK_D_FACTURA				PRIMARY KEY(NUMERO, MINERAL_CODIGO),
	CONSTRAINT FK_D_FACTURA_C_FACTURA	FOREIGN KEY(NUMERO) REFERENCES PUBLIC.SC_FACTURA(NUMERO),
	CONSTRAINT FK_D_ASIENTO_MINERAL		FOREIGN KEY(MINERAL_CODIGO) REFERENCES PUBLIC.MX_MINERAL(CODIGO)
);