CREATE TABLE PUBLIC.MH_YACIMIENTO(
	ID				NUMERIC(4)		NOT NULL UNIQUE,
	NOMBRE			VARCHAR(40)		NOT NULL,
	TIPO			VARCHAR(9)		NOT NULL,
	MAX_KG_ESTIMADO	NUMERIC(10,3)	NOT NULL,
	MINERAL_CODIGO	NUMERIC(2)		NOT NULL,
	
	CONSTRAINT PK_YACIMIENTO 			PRIMARY KEY(ID),
	CONSTRAINT FK_YACIMIENTO_MINERAL	FOREIGN KEY(MINERAL_CODIGO)	REFERENCES PUBLIC.MX_MINERAL(CODIGO),
	CONSTRAINT CK_YACIMIENTO_TIPO		CHECK(TIPO IN ('Autóctono', 'Alóctono'))
);