CREATE TABLE PUBLIC.TD_ASIENTO(
	REF				NUMERIC(8)		NOT NULL,
	CUENTA_CODIGO	NUMERIC(4)		NOT NULL,
	DEBE			NUMERIC(12,2),
	HABER			NUMERIC(12,2),
	TARJETA_NUMERO	NUMERIC(18),
	
	CONSTRAINT PK_D_ASIENTO			PRIMARY KEY(REF, CUENTA_CODIGO),
	CONSTRAINT FK_D_ASIENTO_CUENTA	FOREIGN KEY(CUENTA_CODIGO) REFERENCES PUBLIC.TL_CUENTA(CODIGO),
	CONSTRAINT CK_D_ASIENTO_LADO	CHECK((DEBE IS NOT NULL AND HABER IS NULL) OR (DEBE IS NULL AND HABER IS NOT NULL))
);