CREATE TABLE PUBLIC.MX_MAQUINARIA(
	ID					NUMERIC(4)		NOT NULL UNIQUE,
	NOMBRE				VARCHAR(30)		NOT NULL,
	DESCRIPCION			VARCHAR(100)	NOT NULL,
	CANTIDAD			NUMERIC(6)		NOT NULL,
	EMPRESA_RIF			NUMERIC(10),
	
	CONSTRAINT PK_MAQUINARIA			PRIMARY KEY(ID),
	CONSTRAINT FK_MAQUINARIA_EMPRESA	FOREIGN KEY(EMPRESA_RIF) REFERENCES PUBLIC.CX_EMPRESA(RIF)
);