CREATE TABLE PUBLIC.TL_CUENTA(
	CODIGO		NUMERIC(4)	NOT NULL UNIQUE,
	NOMBRE		VARCHAR(30)	NOT NULL,
	CATEGORIA	VARCHAR(7)	NOT NULL,
	
	CONSTRAINT PK_CUENTA 			PRIMARY KEY(CODIGO),
	CONSTRAINT CK_CUENTA_CATEGORIA	CHECK(CATEGORIA IN ('ACTIVO','PASIVO','CAPITAL','INGRESO','EGRESO'))
);