CREATE TABLE PUBLIC.MX_MINERAL(
	CODIGO		NUMERIC(2)		NOT NULL UNIQUE,
	NOMBRE		VARCHAR(15)		NOT NULL,
	KG_HABIDOS	NUMERIC(10,3)	NOT NULL,
	METALICO	BOOLEAN			NOT NULL,
	
	CONSTRAINT PK_MINERAL PRIMARY KEY(CODIGO)
);