CREATE TABLE PUBLIC.EX_USUARIO(
	EMPLEADO_CI	VARCHAR(10)	NOT NULL UNIQUE,
	NOMBRE		VARCHAR(40)	NOT NULL,
	CLAVE		VARCHAR(20)	NOT NULL,
	ESTATUS		CHAR(1)		NOT NULL,
	
	CONSTRAINT PK_USUARIO PRIMARY KEY (EMPLEADO_CI),
	CONSTRAINT FK_USUARIO_EMPLEADO FOREIGN KEY(EMPLEADO_CI) REFERENCES PUBLIC.EX_EMPLEADO(CI),
	CONSTRAINT CK_USUARIO_ESTATUS CHECK(ESTATUS IN ('A', 'I'))
);