CREATE TABLE PUBLIC.PX_ACTIVIDAD(
	PROYECTO_ID		NUMERIC(8)	NOT NULL,
	FASE_ID			NUMERIC(2)	NOT NULL,
	NUMERO			NUMERIC(2)	NOT NULL,
	NOMBRE			VARCHAR(40)	NOT NULL,
	DESCRIPCION		TEXT		NOT NULL,
	FECHA_INICIO	DATE		NOT NULL,
	FECHA_FIN_EST	DATE		NOT NULL,
	FECHA_FIN		DATE,
	ESTATUS			CHAR(1)		NOT NULL,
	
	CONSTRAINT PK_ACTIVIDAD			PRIMARY KEY(PROYECTO_ID, FASE_ID, NUMERO),
	CONSTRAINT FK_ACTIVIDAD_FASE	FOREIGN KEY(PROYECTO_ID, FASE_ID) REFERENCES PUBLIC.PX_FASE(PROYECTO_ID, ID),
	CONSTRAINT CK_ACTIVIDAD_ESTATUS	CHECK(ESTATUS IN ('A', 'I', 'F', 'N'))
);