CREATE TABLE PUBLIC.MX_MAQUINARIA(
	ID					NUMERIC(4)		NOT NULL UNIQUE,
	NOMBRE				VARCHAR(30)		NOT NULL,
	DESCRIPCION			VARCHAR(100)	NOT NULL,
	CANTIDAD			NUMERIC(6)		NOT NULL,
	
	CONSTRAINT PK_MAQUINARIA	PRIMARY KEY(ID)
);