CREATE TABLE PUBLIC.PX_PARTICIPANTE(
	PROYECTO_ID			NUMERIC(8)	NOT NULL,
	FASE_ID				NUMERIC(2)	NOT NULL,
	ACTIVIDAD_NUMERO	NUMERIC(2)	NOT NULL,
	EMPLEADO_CI			VARCHAR(10)	NOT NULL,
	APROBADO			BOOLEAN		NOT NULL DEFAULT FALSE,
	ROL_CODIGO			NUMERIC(2)	NOT NULL,
	
	CONSTRAINT PK_PARTICIPANTE 				PRIMARY KEY(PROYECTO_ID, FASE_ID, ACTIVIDAD_NUMERO, EMPLEADO_CI),
	CONSTRAINT FK_PARTICIPANTE_ACTIVIDAD	FOREIGN KEY(PROYECTO_ID, FASE_ID, ACTIVIDAD_NUMERO)	REFERENCES PUBLIC.PX_ACTIVIDAD(PROYECTO_ID, FASE_ID, NUMERO),
	CONSTRAINT FK_PARTICIPANTE_EMPLEADO		FOREIGN KEY(EMPLEADO_CI)							REFERENCES PUBLIC.EX_EMPLEADO(CI),
	CONSTRAINT FK_PARTICIPANTE_ROL 			FOREIGN KEY(ROL_CODIGO)								REFERENCES PUBLIC.PL_ROL(CODIGO)
);