CREATE TABLE PUBLIC.EL_CARGO(
	CODIGO				NUMERIC(2)	NOT NULL,
	NOMBRE				VARCHAR(40)	NOT NULL,
	DESCRIPCION			TEXT		NOT NULL,
	DEPARTAMENTO_NUMERO	NUMERIC(4)	NOT NULL,
	
	CONSTRAINT PK_CARGO PRIMARY KEY(CODIGO),
	CONSTRAINT FK_ROL_DEPARTAMENTO FOREIGN KEY(DEPARTAMENTO_NUMERO) REFERENCES PUBLIC.EL_DEPARTAMENTO(NUMERO)
)