CREATE TABLE PUBLIC.EX_HORARIO(
	CODIGO		NUMERIC(3)	NOT NULL UNIQUE,
	DIA			CHAR(1)		NOT NULL,
	HORA_INICIO	TIME		NOT NULL,
	HORA_FIN	TIME		NOT NULL,
	
	CONSTRAINT PK_HORARIO 		PRIMARY KEY(CODIGO),
	CONSTRAINT CK_HORARIO_DIA	CHECK(DIA IN ('L', 'M', 'X', 'J', 'V', 'S', 'D'))
);